version: '3.5'
services:
  app:
    build: .
    environment:
      - SITE_URL=http://app:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=moodle

  sut:
    image: alpine:latest
    depends_on:
      - app
    environment:
      - SOURCE_BRANCH
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
